### ISSUE TITLE
Update more SF Pro Variant

### ISSUE THREAD

**Issue by 3xploiton3** [sahibjotsaggu/San-Francisco-Pro-Fonts#10]
SF-Pro-Italic
SF-Pro-Medium
SF-Pro-Semibold

**Comment by JNGLHAUS** [comment]
Yes I would love to see these as well please!

**Comment by Mqxx** [comment]
- [`SF-Pro-Italic.ttf`](https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts/blob/master/SF-Pro-Italic.ttf) does exist.
- `SF-Pro-Medium` is missing.
- `SF-Pro-Semibold` is missing.
