### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by kadir950** [sahibjotsaggu/San-Francisco-Pro-Fonts#4]
2MB is too big for a single .otf font file. Why are the file sizes so big?

**Comment by Eldrick99** [comment]
True...

**Comment by aisgbnok** [comment]
[If you download them directly from Apple,](https://developer.apple.com/fonts/) all of them are at least `3 MB` in size.

The author of this repository is just uploading what Apple provides.

*As of January 29th 2023, the current version being `18.0d12e2`.*
