### ISSUE TITLE
executable files

### ISSUE THREAD

**Issue by ghost** [sahibjotsaggu/San-Francisco-Pro-Fonts#6]
Could anybody enlighten me as to why each of these font files contain executables?

**Comment by different55** [comment]
Maybe you could first enlighten us why you have that impression?

**Comment by joshxyzhimself** [comment]
@different55 I guess that one beside file size lol

![image](https://user-images.githubusercontent.com/60829711/170844313-3e1e031f-b5e1-484a-869f-ecb38cccd51f.png)

**Comment by different55** [comment]
@joshxyzhimself Ah that's understandable. And poorly explained by GitHub. That means the file *is* executable, not that it is *an* executable. It means the +x bit was set on it, that's all. If you tried to run it, nothing would happen:

<img width="705" alt="Screen Shot 2022-05-28 at 5 18 10 PM" src="https://user-images.githubusercontent.com/585419/170844463-8389e822-e10d-4164-915c-6b76905c74c4.png">

If you want to verify, check out [this repo](https://github.com/LussacZheng/you-get.exe/blob/master/bin/dos2unix.exe). They're hosting an actual .exe file and that label's nowhere to be found cause UNIX-style permissions aren't really a thing on Windows.
