### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by aisgbnok** [sahibjotsaggu/San-Francisco-Pro-Fonts#9]
### Description

Not high priority, but in recent years [`main` has been favored as the default branch of most repositories instead of `master`.](https://github.com/github/renaming) For example if you look at [Microsoft Terminal](https://github.com/microsoft/terminal), they use `main` as their default branch name.

Therefore, to match this new industry standard, I suggest that this repository's default branch name should be changed from `master` to `main`. [This change can be done directly in GitHub](https://github.com/github/renaming#renaming-existing-branches) at the discretion of @sahibjotsaggu. Thank you!

**Comment by P4KM4N** [comment]
This is woke shit. Master is fine.
